/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Thursday, December 23, 2010 at 10:16:12 AM
   By task: Import Data

   Input Data: #LN00014
   Server:  SASMain Plataforma Analitica
   ------------------------------------------------------------------- */

%_eg_conditional_dropds(WORK.FRAUDES2);
%MACRO _EG_ImportData;

%LET IsMVS=FALSE;
DATA _NULL_;
	IF TRIM(SYMGET("SYSSCP")) = "OS" THEN
		IF GETOPTION("FILESYSTEM") = "MVS" THEN
			CALL SYMPUT("IsMVS", "TRUE");
  STOP;
RUN;

OPTIONS DATESTYLE=DMY;
DATA WORK.FRAUDES2;
/* Enterprise Guide creates this temporary asterisk delimited text file from the original data source */
	INFILE #LN00014
		DELIMITER='*'
		MISSOVER
		DSD
	%IF &IsMVS=FALSE %THEN %DO;
		LRECL=32767
	%END;
		FIRSTOBS=2
	;
	LENGTH
		FOLIO $ 10
		CUENTA $ 16
		REFERENCIA $ 25
		COMDETALLE $ 25
		ADTE $ 4
		FOPER 8
		FALTA 8
		SOL $ 2
		FSOL 8
		MES_SOL $ 15
		BRUTO 8
		_T_BRUTO $ 12
		AFILIACION $ 25
		TIPO_DE_FRAUDE $ 8
		AREA $ 7
		DESTINO_CONTABLE $ 33
		PRODUCTO $ 8
		AUTH $ 12
		'Tipo Rec'n $ 4
		'$REC'n 8
		'_T_$REC'n $ 12
		NETO 8
		_T_NETO $ 12
		'Visa/MC'n $ 4
		CTAS $ 8
		Running $ 8
		TFRA $ 15
		REGION $ 4
		MODO $ 9

		_W_StringValue $ 22
;
	INFORMAT
		FOPER DDMMYY10.0
		FALTA DDMMYY10.0
		FSOL DDMMYY10.0
;
	FORMAT
		FOPER DATE9.0
		FALTA DATE9.0
		FSOL DATE9.0
;
	INPUT
		FOLIO $
		CUENTA $
		REFERENCIA $
		COMDETALLE $
		ADTE $
		FOPER : ANYDTDTM22.
		FALTA : ANYDTDTM22.
		SOL $
		FSOL : ANYDTDTM22.
		MES_SOL $
		_T_BRUTO $
		AFILIACION $
		TIPO_DE_FRAUDE $
		AREA $
		DESTINO_CONTABLE $
		PRODUCTO $
		AUTH $
		'Tipo Rec'n $
		'_T_$REC'n $
		_T_NETO $
		'Visa/MC'n $
		CTAS $
		Running $
		TFRA $
		REGION $
		MODO $
;
	DROP
		_T_BRUTO
		'_T_$REC'n
		_T_NETO

		_W_StringValue
		_W_NumericValue
;
	LABEL
		FOLIO = "FOLIO"
		CUENTA = "CUENTA"
		REFERENCIA = "REFERENCIA"
		COMDETALLE = "COMDETALLE"
		ADTE = "ADTE"
		FOPER = "FOPER"
		FALTA = "FALTA"
		SOL = "SOL"
		FSOL = "FSOL"
		MES_SOL = "MES SOL"
		BRUTO = "BRUTO"
		AFILIACION = "AFILIACION"
		TIPO_DE_FRAUDE = "TIPO DE FRAUDE"
		AREA = "AREA"
		DESTINO_CONTABLE = "DESTINO CONTABLE"
		PRODUCTO = "PRODUCTO"
		AUTH = "AUTORIZACION"
		'Tipo Rec'n = "Tipo Rec"
		'$REC'n = "REC$"
		NETO = "NETO"
		'Visa/MC'n = "VISA/MC"
		CTAS = "CTAS"
		Running = "RUNN"
		TFRA = "TFRA"
		REGION = "REGION"
		MODO = "MODO"
;

	FOPER = DATEPART(FOPER);

	FALTA = DATEPART(FALTA);

	FSOL = DATEPART(FSOL);

	_W_StringValue = _T_BRUTO;
	LINK CheckForLogicValue;
	BRUTO = _W_NumericValue;

	_W_StringValue = '_T_$REC'n;
	LINK CheckForLogicValue;
	'$REC'n = _W_NumericValue;

	_W_StringValue = _T_NETO;
	LINK CheckForLogicValue;
	NETO = _W_NumericValue;

RETURN;

/* Requires _W_StringValue to be set with the value to be checked */
/* for a value of 'True' or 'False'. If neither is found, an      */
/* attempt is made to extract a numeric value from the string.    */
/* The extracted value is returned in _W_NumericValue.            */
CheckForLogicValue:
	IF UPCASE(TRIM(_W_StringValue)) = "TRUE" THEN
		_W_NumericValue = 1;
	ELSE
		IF UPCASE(TRIM(_W_StringValue)) = "FALSE" THEN
			_W_NumericValue = 0;
		ELSE
			_W_NumericValue = INPUT(_W_StringValue, COMMA32.);
RETURN;

RUN;
%MEND;
%_EG_ImportData
/* -------------------------------------------------------------------
   End of task code.
   ------------------------------------------------------------------- */
RUN; QUIT;
TITLE; FOOTNOTE;
RUN;

data prevfra1.fraudes_nov;
set fraudes2;
run;
proc sql;/*2,366 $5,320,479 $4,098,779 */
select count(*),sum(bruto),sum(neto) FROM prevfra1.fraudes_nov;
quit;run;