libname prevfra1 '/saspac';
libname prevfra2 '/saspac2/prevencion_fraudes'; /*2009*/
libname prevfra3 '/saspac/prevencion_fraudes'; 

PROC SQL; /*31,507,520*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_OCT2010 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, A.cajero, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA1.POBLACION_MATCH_OCT2010 
			where origen='0074' and resp='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 10 and YEAR(foper) = 2010)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; /*30,436,539*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_SEP2010 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, A.cajero, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA1.POBLACION_MATCH_SEP2010 
			where origen='0074' and resp='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 9 and YEAR(foper) = 2010)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; /*31,078,199*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_AGO2010 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, A.cajero, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA1.POBLACION_MATCH_AGO2010 
			where origen='0074' and resp='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 8 and YEAR(foper) = 2010)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; /*30,331,016*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_JUL2010 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, A.cajero, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA3.ATM201007
			where origen='0074' and resp='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 7 and YEAR(foper) = 2010)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; /*29,906,795*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_JUN2010 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, A.cajero, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA1.POBLACION_MATCH_JUN2010 
			where origen='0074' and resp='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 6 and YEAR(foper) = 2010)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; /*27,864,132*/
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_NOV2009 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, 
			compress(SUBSTR(A.AFIL,1,LENGTH(A.AFIL)-4)) AS CAJERO, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA2.POBLACION_MATCH_NOV2009 
			where origen='0074' and substr(resp,1,2)='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 11 and YEAR(foper) = 2009)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;
PROC SQL; 
	CREATE TABLE PREVFRA1.POBLACION_REMATCH_DIC2009 (COMPRESS=YES)
	AS 
	SELECT 	A.cuenta, A.FECHA_TXS, A.hora, A.monto, compress(CAJERO) AS CAJERO, A.auth,
    		CASE 	WHEN	A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH
					THEN 	1 
					ELSE 	0 
			END AS FRAUDE
      FROM 	(select * 
			from PREVFRA2.POBLACION_MATCH_DIC2009 
			where origen='0074' and substr(resp,1,2)='OK')	A 
      LEFT JOIN (select * 
					from fraudes0910llaves
					where MONTH(foper) = 12 and YEAR(foper) = 2009)	B
	  ON A.CUENTA=B.CUENTA and A.FECHA_TXS=B.FOPER and A.AUTH=B.AUTH;
QUIT;
run;

PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_DIC2009;
TABLES FRAUDE;
RUN;

PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_NOV2009;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_DIC2009;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_ENE2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_FEB2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_MAR2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_ABR2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_MAY2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_JUN2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_JUL2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_AGO2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_SEP2010;TABLES FRAUDE;RUN;
PROC FREQ DATA=PREVFRA1.POBLACION_REMATCH_OCT2010;TABLES FRAUDE;RUN;